import type { Metadata } from "next";
import { Ropa_Sans } from "next/font/google";
import "./globals.css";

const ropaSans = Ropa_Sans({
  variable: "--font-ropa-sans",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ropaSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
